### PR TITLE
[bug 1167241] Add provider and provider_version to Link

### PR DESCRIPTION
**Pull request by willkg**
Quick r?

### CODE REVIEW

**Comment by rlr** [comment]
Is this for analytics?

**Comment by rlr** [comment]
ran tests locally. r+ w/ travis

**Comment by willkg** [comment]
Yeah. It makes it easier for me to know which provider and version a link came from after I persist them to the db. I'll be making other changes soon.

**Comment by willkg** [comment]
Yay travis!

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
