### PR TITLE
1143881 prefill

### PR DESCRIPTION
**Pull request by willkg**
r?

### CODE REVIEW

**Comment by willkg** [comment]
To test by hand:

1. go to http://localhost:8000/feedback/?happy=0
2. pick a product, make sure you land on the more-info page
3. submit
4. make sure the resulting response is sad

Also this to make sure the user can override the prefill:

1. go to http://localhost:8000/feedback/?happy=0
2. pick a product and make sure you land on the more-info page
3. click on the browser back button and make sure you go back to the sentiment page
4. pick "happy"
5. fill out a description and submit
6. make sure the resulting response is happy

You can also run the smoketests, but if they're not working well for you then it's 3 minutes of noise.

**Comment by rlr** [comment]
Do you need to do something additional for FxOS since it's a separate form? It doesn't seem to handle it for me.

**Comment by rlr** [comment]
Other than that, this is working. If that is expected, r+

**Comment by willkg** [comment]
My bad--I should have mentioned that I didn't implement this for Firefox OS--just for all the non-Firefox OS products. I'm not sure this is necessary for Firefox OS, so I just left it out for now.

**Comment by willkg** [comment]
5eaa494 [bug 1143881] Add happy pre-filling via url

Thank you!

**Pull request merged**
