### PR TITLE
[bug 1123746] Add ES 1.2.4 testing to travis test runs

### PR DESCRIPTION
**Pull request by willkg**
Work in progress. Tweaking Travis configuration.

### CODE REVIEW

**Comment by willkg** [comment]
Well, that was easy!

r?

**Comment by willkg** [comment]
If you check the Travis Details, it ran the tests twice: once with ES 0.90.10 (yay!) and once with ES 1.2.4 (yay!). So... looks like we're good to go.

**Comment by rlr** [comment]
hot :fire: r+

**Comment by willkg** [comment]
db365f4 [bug 1123746] Add ES 1.2.4 testing to travis test runs

Thank you!

**Pull request merged**
