### PR TITLE
bug 1193323 : Remove eq_ and ok_ : base

### PR DESCRIPTION
**Pull request by staranjeet**
This commit removes eq_ and ok_ imports as well as their use in the
files. It replaces eq_ and ok_ with proper assert statements.

### CODE REVIEW

**Comment by willkg** [comment]
This looks good to me! r+

**Comment by willkg** [comment]
Thank you!

**Comment by staranjeet** [comment]
That marks my first contribution to Mozilla.

**Comment by willkg** [comment]
Congratulations!

**Pull request merged**
