### PR TITLE
[bug 1130762] Alerts app, models and modelfactories

### PR DESCRIPTION
**Pull request by willkg**
This is the gist of the Alerts app.

r?

### CODE REVIEW

**Comment by willkg** [comment]
This doesn't have any tests. Mostly it's a db schema.

When reviewing, just make sure it has the appropriate things for Django models. Otherwise this is sort of a no-op.

**Comment by rlr** [comment]
New app LGTM. I ran the migration and it worked.

Bring on the Alerts! r+

**Comment by willkg** [comment]
0fa0aab [bug 1130762] Alerts app, models and modelfactories

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
