### PR TITLE
1203173 analyzer tests

### PR DESCRIPTION
**Pull request by willkg**
r?

### CODE REVIEW

**Comment by willkg** [comment]
This couples a some code reorganization and code cleanup with addition of tests for analyzer views that didn't have any.

These are basic tests--they mostly test to see if the view "works" and the template "rendered" for the basic situations. They don't test edge cases or complex functionality.

There's still a lot of goofy code that should be rewritten in there. I'm going to push that off to another day.

@mythmon Can you take a look at these?

**Comment by mythmon** [comment]
I didn't look at the views that moved. I assume those are just moves and there weren't any edits. If that's not the case, I can look harder.

The tests look straight forward. Most of the tests seem to have been copy-pasted, which is fine, but it means they have the same oddities. `jane@example.com` is one, and generally having multiple logically independent things in one test is another.

Yay for more tests!

**Comment by willkg** [comment]
That's correct--the views just moved from one place to another. I thought about rewriting them as CBVs, but decided to push that off.

I'll remove the `user__email` stuff in a cleanup commit. At some point, I'll wrap my head around pytest fixtures and use that. Maybe I'll do that now ... Mmm....

**Comment by willkg** [comment]
Oh, wait--I remember: pytest fixtures don't work well with Django TestCase derivatives. So I won't do that.

**Comment by willkg** [comment]
Bah! I'm mis-remembering: fixtures are fine, it's paramaterize that doesn't work so well.

**Comment by willkg** [comment]
Tried to get fixtures to work, but couldn't and decided not to spend more time on it.

Did some minor cleanup. If Travis is green, I'll merge it.

**Comment by willkg** [comment]
Green. Merging!

**Pull request merged**
