### PR TITLE
[bug 1116838] Create waffle flag for thank you page

### PR DESCRIPTION
**Pull request by aokoye**

### CODE REVIEW

**Comment by willkg** [comment]
This looks ok except that we do all waffle flag migrations in the base app:

http://fjord.readthedocs.org/en/latest/db.html#data-migrations-for-data-in-non-fjord-apps

**Comment by aokoye** [comment]
The latest commit should do it. I though I had deleted the initial waffle flag migration in the commit prior but quickly realized that that wasn't the case.

**Comment by willkg** [comment]
Can you squash these commits into one?

**Comment by aokoye** [comment]
I just squashed the commits.

**Comment by willkg** [comment]
Awesome! Thank you!

9921759 [bug 1116838] Create waffle flag for thank you page

**Pull request merged**
