### PR TITLE
[bug 1155890] policy

### PR DESCRIPTION
**Pull request by willkg**
This tweaks the template structure to include the footer on all feedback pages. It fixes the footer to be a macro rather than an include. It cleans up some code that was goofy mostly by removing the things I had questions about. It updates the smoketests to verify that the privacy link is visible on the appropriate cards and goes to the right place.

To review:

1. skim the changes
2. run the tests
3. (optional) run the smoke tests
4. do a run through of the generic feedback form and the fxos feedback form and verify the footer is on the bottom
5. listen to a good song that really embodies Input development; perhaps this one: https://www.youtube.com/watch?v=-wiRivDMIYM

r?

### CODE REVIEW

**Comment by rlr** [comment]
WFM LGTM BBQ MFBT r+

**Comment by willkg** [comment]
travis is erroring out. Mmm... I'm not sure what to do. I think I'm going to err on the side of "wait for travis to be happy" and push this out later.

**Comment by willkg** [comment]
Rrr... one job fails and the other succeeds and they only differ in ES versions which has nothing to do with this change.

**Comment by willkg** [comment]
Yay! PASSED!

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
