### PR TITLE
1165996 description

### PR DESCRIPTION
**Pull request by willkg**
r?

### CODE REVIEW

**Comment by willkg** [comment]
Pretty sure this is straight forward. I don't remember offhand why it was set for `blank=True` originally. Seems like it was a mistake.

**Comment by mythmon** [comment]
Travis :exclamation:. Though looking at it, it is probably a transient failure. I'll restart it.

Wasn't there some source of feedback in the past that would only report sad/happy, but not give any description? That would explain why this was set to blank=True.

**Comment by willkg** [comment]
I don't recall one. There are only 617 responses that have an empty string description in the db, so I suspect it's just a mistake.

**Comment by willkg** [comment]
Travis passed. Yippie yay!

**Comment by mythmon** [comment]
Yay, r+

**Comment by willkg** [comment]
^^^ Rebased against master.

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
