### PR TITLE
1093857 pytest

### PR DESCRIPTION
**Pull request by willkg**
This switches Fjord to use py.test.

r?

### CODE REVIEW

**Comment by willkg** [comment]
^^^ Lots of travis failures. I'll have to look into why they're failing on travis, but not locally.

**Comment by willkg** [comment]
^^^ fixes travis and also removes some debugging stuff i had in one of the suggest tests. That should be good to go.

**Comment by rlr** [comment]
so awesome!

**Comment by rlr** [comment]
For some reason I expected the requirements to be in vendor. Not sure why I had that expectation, once I updated my virtualenv it was all good. r+

```
======================================== short test summary info =========================================
SKIP [1] /Users/rlr/.virtualenvs/fjord/lib/python2.7/site-packages/_pytest/skipping.py:140: LIVE_API not in environ
SKIP [2] /Users/rlr/.virtualenvs/fjord/lib/python2.7/site-packages/_pytest/skipping.py:140: no gengo creds

================================= 312 passed, 3 skipped in 20.63 seconds ================================
```

**Comment by willkg** [comment]
Oh, my bad! Yeah, the requirements for testing are in ``requirements/dev.txt` now. We had the nose stuff in vendor since django-nose had to be an INSTALLED_APP. Blech.

**Pull request merged**
