### PR TITLE
[bug 1112096] Add journal purging; rewrite data purging system

### PR DESCRIPTION
**Pull request by willkg**
This rewrites the data purging system so that it's project-wide
infrastructure.

It also adds data purging for the journal.

r?

### CODE REVIEW

**Comment by willkg** [comment]
@mythmon Can you look this over?

**Comment by mythmon** [comment]
This looks fine to me. r+

**Comment by willkg** [comment]
^^^ Rebase against master (just in case--there's been a bunch of changes).

Will wait for travis and then land it.

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
