### PR TITLE
[bug 1120952] Fix remotetroubleshooting metrics

### PR DESCRIPTION
**Pull request by willkg**
* nixes the optout metric since it's wrong and hard to get right without
  duplicating code
* further, I added email optin metrics and context metrics

Quick r?

### CODE REVIEW

**Comment by willkg** [comment]
There isn't anything to test here, but a quick eyeball on the code would be good.

**Comment by mythmon** [comment]
:eyes: Yep, those are statsd calls. :+1:

**Comment by willkg** [comment]
f75a942 Fix top-level untranslated_words metrics in l10n_completion

Thank you!

**Comment by willkg** [comment]
Got the commit wrong. It was this one:

60553bc [bug 1120952] Fix remotetroubleshooting metrics

**Pull request merged**
