### PR TITLE
Handle whitespace URLs

### PR DESCRIPTION
**Pull request by willkg**
If a URL consists solely of whitespace, we should strip the whitespace
and store an empty string in the db.

r?

### CODE REVIEW

**Comment by willkg** [comment]
This removes leading/trailing whitespace from the data and then passes it through `clean_url`. The result being that if the url is just whitespace, it'll get saved as an empty string (which is good). Plus we ditch leading/trailing whitespace if it shows up, too.

To review:

1. look through the code changes and test
2. run the tests

**Comment by lgp171188** [comment]
+1

**Comment by lgp171188** [comment]
:+1:

**Comment by rlr** [comment]
r+ too

**Comment by willkg** [comment]
^^^ Squashed those two commits.

**Comment by willkg** [comment]
Landed in: 43ec5da Handle whitespace URLs

Thank you!

**Pull request merged**
