### PR TITLE
[Bug 1118765] Upgrade django to v1.7

### PR DESCRIPTION
**Pull request by rlr**
A bunch of tests are failing. Not sure wtf is going on. But I figured it's good to get this up for more eyeballs.

### CODE REVIEW

**Comment by rlr** [comment]
FTR. The tests are failing because they are missing required data. I'll be working on that next.

**Comment by rlr** [comment]
woohoo. Tests passing and updated db docs. :point_up: :dancers:

**Comment by willkg** [comment]
Just to make sure it's here, too. I just landed a migration, so I think this needs to be updated to pick that up.

**Comment by willkg** [comment]
Why upgrade django-celery to master tip instead of a released version?

Can we move the django-nose to a separate PR to reduce the size of this PR?

**Comment by rlr** [comment]
django-celery hasn't released anything since it added v1.7 support. I think it's kind of unofficially maintained so the long term thing to do is drop it.

**Comment by willkg** [comment]
Ok. Mmm... I think I'd push any of the updates out of this PR so we can work through them first. That reduces the size of the change here and lets us deploy and test smaller parts.

**Comment by rlr** [comment]
Filed pull 484 and pull 485. This PR depends on those to land first so I can rebase and make this look smaller.

**Comment by rlr** [comment]
Added some new migrations to match current master :point_up:

**Comment by willkg** [comment]
I meant to work on this over the weekend, but didn't get a chance.

You moved the django-nose update and the fix to the stale note about test_utils into a PR which was merged, so we can remove those from this PR.

Further, I'd merge the two commits dealing with migrations into one.

Plus every commit should have the bug number in the commit summary.

After all that, I'll work through this. It'd be super if we can get it done today or tomorrow because this is a big change and I don't want to keep pushing it off since other things are changing, too.

**Comment by rlr** [comment]
squashed and rebased :point_up: 

I think we need to deploy the first time with this change:

```
diff --git a/bin/update/update.py b/bin/update/update.py
index 467f05e..ed65bd4 100644
--- a/bin/update/update.py
+++ b/bin/update/update.py
@@ -72,7 +72,7 @@ def update_assets(ctx):
 def update_db(ctx):
     """Update the database schema, if necessary."""
     with ctx.lcd(settings.SRC_DIR):
-        ctx.local(PYTHON + " manage.py migrate --all --noinput")
+        ctx.local(PYTHON + " manage.py migrate --fake --noinput")


 @task
```

**Comment by rlr** [comment]
smoke tests ran: `23 passed, 6 deselected in 80.90 seconds`

**Comment by rlr** [comment]
Added section about reverse migrations :point_up: 

I am game either way for the `deconstruct()` stuff. It is weird and I opted to make it look more like the django codebase. But I can just delete it and update the migrations. It works that way too since I had it originally like that.

**Comment by rlr** [comment]
thanks! added the comment. I'll squash if that's all that was left?

**Comment by willkg** [comment]
I ran through this:

1. verified that all the data migrations that need to be brought over were brought over
2. reviewed the code until the PR looked good to go
3. tested the admin code locally to make sure we didn't need a new grapelli or django-adminplus
4. ran the unit tests with a clean db
5. ran `./manage.py migrate --fake` on a up-to-date db dump
6. submitted feedback and verified it made it to the front page
7. ran esreindex
8. ran the smoketests: 3 failed, but that's another unrelated problem I need to look into and write up a bug for

We need to fix the update script so that it does a `./manage.py migrate --fake` thing instead of trying to actually do migrations. That should be a commit by itself.

Then I think we're good to do a test deploy on -stage.

**Comment by willkg** [comment]
Waiting to merge this until after we've done a test deploy to stage which we're doing now....

**Comment by rlr** [comment]
added the wsgi fix commit and removed the `--fake` from the deploy script :point_up:

**Comment by willkg** [comment]
I'll wait for a travis green light, then merge this.

**Comment by willkg** [comment]
c9a326d [bug 1118765] Run migrations for real during deploy.
1288d5b [bug 1118765] Fix wsgi file
c55ae2c [bug 1118765] Fake the migrations for the first deploy of 1.7
dcd6acb [bug 1118765] Update db docs for django 1.7 (new migration system)
7aa9750 [bug 1118765] Replace south with the new django 1.7 migrations.
fea60dc [bug 1118765] Upgrade django to 1.7.4

Thank you! Awesome work on this!

**Pull request merged**
