### PR TITLE
[bug 1194450] Remove rating

### PR DESCRIPTION
**Pull request by willkg**
Gradients... we hardly knew you.

Quick r?

### CODE REVIEW

**Comment by willkg** [comment]
There was a project to switch from the happy/sad faces to 5 gradations of faces. I started working through the implementation bugs one of which was adding this field to the model. Last quarter, we decided after some thought that we didn't really want to do gradients--it was a lot of work and it wasn't clear what we were getting out of it. Thus we abandoned the project.

This PR removes the column that was added, but never used.

**Comment by willkg** [comment]
@mythmon Can you take a look at this today? It should be straight-forward.

**Comment by mythmon** [comment]
The code changes here look good. Assuming nothing is going to break when those API fields go away (and it sounds like nothing will), I say r+ :boat:.

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
