### PR TITLE
[bug 1163748] Add requests-mock; update six, requests

### PR DESCRIPTION
**Pull request by willkg**
* add requests-mock
* update six to 1.9.0
* update requests to 2.7.0
* fix typos in .pre-commit-config.yaml

r?

### CODE REVIEW

**Comment by willkg** [comment]
This doesn't seem to affect anything adversely. It's in `vendor/packages/` so the changed files is cr-AZY.

My vote is we see how travis feels, then land it.

**Comment by mythmon** [comment]
I looked at the changes in `requirements.txt` and `.pre-commit.yaml`. They look sane. Travis isn't reporting back to GitHub, so we'll have to go look that up manually, but if Travis is happy, I say ship it :ship:.

**Comment by willkg** [comment]
https://travis-ci.org/mozilla/fjord/builds/62134689

**Comment by willkg** [comment]
Actually, instead of landing this, I'm going to go reimplement some test cases with requests-mock to make sure I want to keep it around.

**Comment by willkg** [comment]
^^^ That redoes one of the tests with requests_mock. It doesn't redo all the tests because most of the tests are mocking out GengoAPI and not requests.

Also, Travis says that one is cool.

https://travis-ci.org/mozilla/fjord/builds/62142598

**Comment by willkg** [comment]
I think this looks ok. Going to land it now.

**Pull request merged**
