### PR TITLE
[bug 1108156] Upgrade peep

### PR DESCRIPTION
**Pull request by willkg**
Upgrades to the last peep with the --no-use-wheels provision still in.
Also, this removes the goofy "pip install pip" line.

r?

### CODE REVIEW

**Comment by willkg** [comment]
I think the only way to test this is to destroy your vagrant vm and create a new one.

1. vagrant halt
2. vagrant destroy
3. vagrant up
4. vagrant ssh
5. cd fjord; manage.py test

**Comment by willkg** [comment]
Oops--just found a problem. Working on it now.

**Comment by willkg** [comment]
Ugh. I hit all kinds of problems. I need to test with a fresh vm now.

**Comment by willkg** [comment]
Wow... So that happened. One tiny change turned into a bunch of changes and a bunch of fixes.

The test steps run in the previous comment works. The changes shouldn't affect -dev, -stage and -prod environments.

**Comment by rlr** [comment]
Probably unrelated to this PR, but I get this error:

```
(fjordvagrant)vagrant@vagrant-ubuntu-trusty-64:~/fjord$ ./manage.py test
Using test configuration
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    monkeypatches.patch()
  File "/home/vagrant/fjord/fjord/base/monkeypatches.py", line 32, in patch
    import jingo.monkey
  File "/home/vagrant/.virtualenvs/fjordvagrant/local/lib/python2.7/site-packages/jingo/__init__.py", line 164, in <module>
    env = get_env()
  File "/home/vagrant/.virtualenvs/fjordvagrant/local/lib/python2.7/site-packages/jingo/__init__.py", line 52, in get_env
    loaders = [loader(p) for loader, places in x for p in places]
  File "/home/vagrant/.virtualenvs/fjordvagrant/local/lib/python2.7/site-packages/jinja2/loaders.py", line 216, in __init__
    provider = get_provider(package_name)
  File "/home/vagrant/.virtualenvs/fjordvagrant/local/lib/python2.7/site-packages/pkg_resources.py", line 229, in get_provider
    __import__(moduleOrReq)
ImportError: No module named sslserver
```

I guess I need to install that separately?

**Comment by rlr** [comment]
Oh, that's probably because of my settings_local. Let me fix that.

**Comment by willkg** [comment]
We were using it to test the remote-troubleshooting stuff. It's not in the dev requirements so probably best to undo it in your local.py settings file.

Going forward, we could add that as a requirement to dev.txt. I'm not sure how often it'll come up or what additional complexities it adds especially in the vagrant dev environment.

**Comment by rlr** [comment]
WFM. r+

**Comment by willkg** [comment]
Landed in 342eac3 [bug 1108156] Upgrade peep and handle pip 6.0

Thank you!

**Pull request merged**
