### PR TITLE
1130765 fix

### PR DESCRIPTION
**Pull request by willkg**
This is a recreation of pull #495 which I incorrectly based on a non-master branch.

r?

### CODE REVIEW

**Comment by willkg** [comment]
@mythmon This PR passed Travis. I think we're good to go now. Does that look ok to you?

**Comment by mythmon** [comment]
Yeah, this looks good. I see you also added some error checking for the flavor parameter. That looks good too.

r+

**Comment by mythmon** [comment]
Yeah, this looks good. I see you also added some error checking for the flavor parameter. That looks good too.

r+

**Comment by willkg** [comment]
067d6e8 [bug 1130765] Add support for Fjord-Authorization header
1e1ca9a [bug 1130765] Tweak error msg in case where auth header is missing
6bc619e [bug 1130765] Docs fixes for the alerts api

Thank you!

**Pull request merged**
