### PR TITLE
[bug 1048462] Remove nuggets

### PR DESCRIPTION
**Pull request by willkg**
* switch the import for dictconfig to the django version
* nix nuggets
* specify versions for tower and django-celery neither of which release
  versions

Quick r?

### CODE REVIEW

**Comment by rlr** [comment]
r+

**Comment by willkg** [comment]
I'm going to tweak this so the dictconfig stuff is what kitsune does.

**Comment by willkg** [comment]
^^^ That fixes the import statement to what Kitsune has.

**Comment by rlr** [comment]
:boat: r+

**Comment by willkg** [comment]
4a8de81 [bug 1048462] Remove nuggets

Thank you!

**Pull request merged**
