### PR TITLE
[bug 1177224] Ditch a bunch of half-assed stuff

### PR DESCRIPTION
**Pull request by willkg**
Ditches a bunch of half-implemented things:

* occurrences report
* product dashboards
* hourly report
* spam duplicates report

r?

### CODE REVIEW

**Comment by willkg** [comment]
This is mostly a lot of code removal. None of these things are used by real people as far as I know. There wasn't even tests for most of it.

**Comment by willkg** [comment]
Travis passed it! Yay!

**Comment by rlr** [comment]
yay for cleanup! r+

**Comment by willkg** [comment]
893 lines GONE!

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
