### PR TITLE
[bug 1193321] Remove eq_ and ok_: analytics

### PR DESCRIPTION
**Pull request by staranjeet**
[bug 1193321] Remove eq_ and ok_: analytics
This commit removes eq_ and ok_ imports as well as their use in the
files. It replaces eq_ and ok_ with proper assert statements.

### CODE REVIEW

**Comment by willkg** [comment]
It helps to have the commit message summary in a certain format because that's what all our tools understand. Namely:
```
[bug xxxxxxx] summary goes here
```

For this commit, it'd be:

```
[bug 1193321] Remove eq_ and ok_: analytics
```

I should have caught this in the previous PR, too. My apologies.

**Comment by staranjeet** [comment]
updated and I will take care of this from next time.

**Comment by willkg** [comment]
It's not just the pull request title, but the first line of the commit message, too.

**Comment by staranjeet** [comment]
again updated!

**Comment by willkg** [comment]
It doesn't look like the commit message has been updated. I think you have to fix the commit message in your fork doing something like:

```
git commit --amend
```

then do a force push to update it in the PR:

```
git push -f origin 1193321-remove-eq-ok
```

(assuming the remote is named "origin").

That should update it in the PR.

**Comment by staranjeet** [comment]
Changed the commit message. Now check if the message is updated or not?

**Comment by willkg** [comment]
Awesome--looks good! I'll go through the PR now.

**Comment by willkg** [comment]
Looks great! Thank you!

**Pull request merged**
