### PR TITLE
Add contribute.json file.

### PR DESCRIPTION
**Pull request by Osmose**
Add a contribute.json file à la http://contribute.paas.allizom.org/.

### CODE REVIEW

**Comment by Osmose** [comment]
@willkg r?

**Comment by willkg** [comment]
We've already got one: 

https://github.com/mozilla/fjord/blob/master/fjord/base/templates/contribute.json

**Comment by Osmose** [comment]
Hmm. So http://contribute.paas.allizom.org/ suggests putting it at the root of the repo (since not all projects are websites). Would a symlink in place of that template and moving that file to the repo root be an acceptable compromise?

**Comment by willkg** [comment]
I'm loathe to do symlinks. You mentioned doing a lib at one point, I'd be game for that. Or fixing the view to look at a different file.

**Comment by willkg** [comment]
@Osmose Do you want to keep working on this or should we close it out?

**Comment by Osmose** [comment]
Updated to move the contribute.json file to the root of the repo.

**Comment by willkg** [comment]
Looks good to me! r+

**Pull request merged**
