### PR TITLE
[bug 1118765] Upgrade waffle to v0.10.1 for django 1.7

### PR DESCRIPTION
**Pull request by rlr**
This is a dot release that adds the new migrations for django 1.7.

r?

### CODE REVIEW

**Comment by willkg** [comment]
This is failing with:

```
======================================================================
ERROR: fjord/feedback/tests/test_views.py:TestFeedback.test_browser_data_not_there_when_feedbackdev_is_false
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/mozilla/fjord/fjord/base/tests/__init__.py", line 101, in _give_me_waffles
    except waffle.Flag.DoesNotExist:
AttributeError: 'module' object has no attribute 'Flag'
```

**Comment by rlr** [comment]
huh. That looks goofy. `waffle.Flag` instead of `waffle.models.Flag`?

**Comment by rlr** [comment]
Yeah, this broke it https://github.com/jsocol/django-waffle/commit/c117efe072eaea4fa88cec212b3f15b7b5eccff9

**Comment by rlr** [comment]
fixord ^

**Comment by willkg** [comment]
Great! Can you squash these? Then we'll merge it.

**Comment by rlr** [comment]
done! :point_up:

**Comment by willkg** [comment]
Yay!

b5676cf [bug 1118765] Upgrade waffle to v0.10.1 for django 1.7

**Pull request merged**
