### PR TITLE
[bug 934979] Upgrade django rest framework to v2.4.4

### PR DESCRIPTION
**Pull request by rlr**
This seems to just work. I ran the test suite and tested the Firefox OS feedback flow. Any other critical paths that should be manually tested?

r?

### CODE REVIEW

**Comment by willkg** [comment]
Can you address this, too?:

https://github.com/mozilla/fjord/blob/master/fjord/feedback/tests/test_api.py#L511

**Comment by willkg** [comment]
Did you run the smoketests? If not, that's a good thing to run, too. If all that works, then we're probably fine. When I deploy it, I'll keep tabs on all the things to make sure everything continues to look ok.

**Comment by rlr** [comment]
That commented out test still fails :disappointed:

**Comment by rlr** [comment]
I had one smoketest fail, but I think it's the one that always fails for me. BTW, should we think about running them in travis?

```
============================================= FAILURES ==============================================
_________________________ TestSearchDates.test_feedback_custom_date_filter __________________________

self = <tests.dashboard.test_date_filter.TestSearchDates object at 0x102e5bd90>
mozwebqa = <pytest_mozwebqa.pytest_mozwebqa.TestSetup instance at 0x102e27710>

    @pytest.mark.nondestructive
    def test_feedback_custom_date_filter(self, mozwebqa):
        """

            1. Verifies the calendar is displayed when filtering on custom dates
            2. Verifies date-start=<date> and end-date=<date> in the url

            """
        dashboard_pg = DashboardPage(mozwebqa)

        dashboard_pg.go_to_dashboard_page()

        start_date = date.today() - timedelta(days=3)
        end_date = date.today() - timedelta(days=1)

>       dashboard_pg.date_filter.filter_by_custom_dates_using_datepicker(start_date, end_date)

tests/dashboard/test_date_filter.py:75:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pages.regions.date_filter.DateFilter object at 0x102e5bf10>
start_date = datetime.date(2015, 1, 26), end_date = datetime.date(2015, 1, 28)

    def filter_by_custom_dates_using_datepicker(self, start_date, end_date):
        """Filters by a custom date range."""
        self.enable_custom_dates()
>       self.select_custom_start_date_using_datepicker(start_date)

pages/regions/date_filter.py:175:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pages.regions.date_filter.DateFilter object at 0x102e5bf10>
date = datetime.date(2015, 1, 26)

    def select_custom_start_date_using_datepicker(self, date):
>       self.click_start_date()

pages/regions/date_filter.py:165:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pages.regions.date_filter.DateFilter object at 0x102e5bf10>

    def click_start_date(self):
        """Clicks the start date in the custom date filter form and waits for the datepicker to appear."""
        self.selenium.find_element(*self._custom_start_date_locator).click()
>       self.wait_for_datepicker_to_open()

pages/regions/date_filter.py:99:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pages.regions.date_filter.DateFilter object at 0x102e5bf10>

    def wait_for_datepicker_to_open(self):
>       WebDriverWait(self.selenium, self.timeout).until(lambda s: self.is_datepicker_visible)

pages/regions/date_filter.py:86:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.support.wait.WebDriverWait object at 0x102e5be50>
method = <function <lambda> at 0x102e62050>, message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
            return value is not False."""
        end_time = time.time() + self._timeout
        while(True):
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions:
                pass
            time.sleep(self._poll)
            if(time.time() > end_time):
                break
>       raise TimeoutException(message)
E       TimeoutException: Message: ''

../../../.virtualenvs/fjord-smoketests/lib/python2.7/site-packages/selenium/webdriver/support/wait.py:71: TimeoutException
------------------------------------------ pytest-mozwebqa ------------------------------------------
Failing URL: http://localhost:8000/en-US/
```

**Comment by willkg** [comment]
That smoke test isn't related to API stuff, so that's "fine". For the record, before running the smoke tests, you should generate new data and then reindex:

https://github.com/mozilla/fjord/tree/master/smoketests#running-tests-against-localhost

I'm puzzled that the commented-out test still fails. I thought that'd be fixed.

I created bug #1127428 to look into that test and why it's still failing.

The rest of this is probably good to go now.

**Comment by willkg** [comment]
6fe9630 [bug 934979] Upgrade django rest framework to v2.4.4

**Pull request merged**
