### PR TITLE
[bug 1091716] Carry changes over to generic_feedback_dev.js

### PR DESCRIPTION
**Pull request by willkg**
In bug #1091716, we updated
fjord/feedback/static/js/generic_feedback.js. However, because we're in
the middle of the remote-troubleshooting changes, we have a parallel
generic_feedback_dev.js file which has the remote-troubleshooting
changes and is currently "live".

This commit updates the generic_feedback_dev.js file with the changes we
made to generic_feedback.js.

r?

### CODE REVIEW

**Comment by willkg** [comment]
This should mirror the changes in fff110199916dc10215629551b7b1e922eb37f12

**Comment by rlr** [comment]
looks good. smoke tests now pass for me. r+

**Comment by willkg** [comment]
Awesome! Thank you!

**Comment by willkg** [comment]
7cf5b3c [bug 1091716] Carry changes over to generic_feedback_dev.js

**Pull request merged**
